import fs from 'node:fs';
import path from 'node:path';
import http from 'node:http';
import {spawn,spawnSync} from 'node:child_process';
import {settings} from './config.mjs';
import {statePath} from './paths.mjs';

const nowIso=()=>new Date().toISOString();
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const repairFile=()=>statePath('edge-repair-v34.json');
const evidenceFile=()=>statePath('edge-repair-v34-last.json');
function edgeExe(){return process.env.DUO_EDGE_EXE||'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe'}
export function edgeUserDataDir(){return process.env.DUO_EDGE_USER_DATA_DIR||(process.platform==='win32'&&process.env.LOCALAPPDATA?path.join(process.env.LOCALAPPDATA,'Microsoft','Edge','User Data'):'')}
function activePortFile(){const d=edgeUserDataDir();return d?path.join(d,'DevToolsActivePort'):''}
export function readActivePort(){try{const f=activePortFile();if(!f)return null;const l=fs.readFileSync(f,'utf8').trim().split(/\r?\n/);const port=Number(l[0]);if(!port)return null;return {port,wsPath:String(l[1]||'').trim(),file:f,userDataDir:edgeUserDataDir()}}catch{return null}}
function httpJson(port,p='/json/version',timeout=1000){return new Promise(resolve=>{const q=http.get({host:'127.0.0.1',port,path:p,timeout},r=>{let s='';r.on('data',c=>{if(s.length<100000)s+=c});r.on('end',()=>{try{resolve({ok:r.statusCode===200,json:JSON.parse(s)})}catch{resolve({ok:false,status:r.statusCode})}})});q.on('timeout',()=>{q.destroy();resolve({ok:false,error:'TIMEOUT'})});q.on('error',e=>resolve({ok:false,error:e.code||e.message}))})}
function psJson(script,timeout=12000){if(process.platform!=='win32')return null;const r=spawnSync('powershell.exe',['-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-Command',script],{encoding:'utf8',windowsHide:true,timeout});if(r.status!==0)return null;const t=String(r.stdout||'').trim();if(!t)return [];try{return JSON.parse(t)}catch{return null}}
export function topEdgeProcesses(){const j=psJson(`@(Get-CimInstance Win32_Process -Filter "Name='msedge.exe'" | Where-Object { $_.CommandLine -notmatch '--type=' } | Select-Object ProcessId,ParentProcessId,CommandLine) | ConvertTo-Json -Compress`);const a=Array.isArray(j)?j:(j?[j]:[]);return a.map(x=>({pid:Number(x.ProcessId)||0,parentPid:Number(x.ParentProcessId)||0,commandLine:String(x.CommandLine||'')}))}
function personalEdges(){return topEdgeProcesses().filter(x=>!x.commandLine.toLowerCase().includes('\\agente-navegador\\dominici-platform\\data\\browser-profile'))}
function readRepair(){try{return JSON.parse(fs.readFileSync(repairFile(),'utf8'))}catch{return {bootKey:null,restarts:0,lastAt:null}}}
function writeRepair(j){try{fs.writeFileSync(repairFile(),JSON.stringify(j,null,2),'utf8')}catch{}}
function bootKey(){if(process.platform!=='win32')return 'nonwin';const j=psJson(`$o=Get-CimInstance Win32_OperatingSystem; @{boot=$o.LastBootUpTime.ToString('o')} | ConvertTo-Json -Compress`);return String(j?.boot||'unknown')}
function backupSessions(){const ud=edgeUserDataDir();if(!ud)return null;const stamp=new Date().toISOString().replace(/[:.]/g,'-');const base=path.join(path.dirname(statePath('x')),'edge-recovery',stamp);try{fs.mkdirSync(base,{recursive:true});for(const rel of ['Local State',path.join('Default','Preferences')]){const s=path.join(ud,rel),d=path.join(base,rel);if(fs.existsSync(s)){fs.mkdirSync(path.dirname(d),{recursive:true});try{fs.copyFileSync(s,d)}catch{}}}const ses=path.join(ud,'Default','Sessions');if(fs.existsSync(ses))try{fs.cpSync(ses,path.join(base,'Sessions'),{recursive:true,force:true})}catch{};return base}catch{return null}}
function legacySources(){if(process.platform!=='win32')return [];const script=`$o=@(); $rk='HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run'; if(Test-Path $rk){$p=Get-ItemProperty $rk; foreach($x in $p.PSObject.Properties){if($x.Name -notmatch '^PS' -and [string]$x.Value -match 'remote-debugging-port=9222|msedge(.exe)?' -and ([string]$x.Value -match 'ROBOT|agente-navegador|DUO|Dominici')){$o += [pscustomobject]@{kind='RUN';name=$x.Name;value=[string]$x.Value}}}}; try{Get-ScheduledTask | ForEach-Object {$t=$_; foreach($a in $t.Actions){$z=([string]$a.Execute+' '+[string]$a.Arguments);if($z -match 'remote-debugging-port=9222|msedge(.exe)?' -and ($z -match 'ROBOT|agente-navegador|DUO|Dominici' -or $t.TaskName -match 'DUO|Dominici')){$o += [pscustomobject]@{kind='TASK';name=$t.TaskName;value=$z}}}}}catch{}; @($o) | ConvertTo-Json -Compress`;const j=psJson(script,20000);return Array.isArray(j)?j:(j?[j]:[])}
function neutralizeLegacy(sources){if(process.platform!=='win32'||!settings.browserBridge?.legacyLauncherNeutralize)return [];const out=[];for(const x of sources){try{if(x.kind==='RUN'){const safe=String(x.name).replace(/'/g,"''");const r=spawnSync('powershell.exe',['-NoProfile','-NonInteractive','-Command',`Remove-ItemProperty -Path 'HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Run' -Name '${safe}' -ErrorAction SilentlyContinue`],{encoding:'utf8',windowsHide:true,timeout:8000});out.push({kind:'RUN',name:x.name,disabled:r.status===0})}else if(x.kind==='TASK'){const safe=String(x.name).replace(/'/g,"''");const r=spawnSync('powershell.exe',['-NoProfile','-NonInteractive','-Command',`Disable-ScheduledTask -TaskName '${safe}' -ErrorAction SilentlyContinue | Out-Null`],{encoding:'utf8',windowsHide:true,timeout:8000});out.push({kind:'TASK',name:x.name,disabled:r.status===0})}}catch{out.push({kind:x.kind,name:x.name,disabled:false})}}return out}
function gracefulClosePersonalEdge(){if(process.platform!=='win32')return false;const script=`$roots=@(Get-CimInstance Win32_Process -Filter "Name='msedge.exe'" | Where-Object { $_.CommandLine -notmatch '--type=' -and $_.CommandLine -notmatch 'agente-navegador\\\\dominici-platform\\\\data\\\\browser-profile' }); $pids=@($roots.ProcessId); Get-Process msedge -ErrorAction SilentlyContinue | Where-Object {$_.MainWindowHandle -ne 0} | ForEach-Object {try{$_.CloseMainWindow() | Out-Null}catch{}}; Start-Sleep -Seconds 5; foreach($id in $pids){if(Get-Process -Id $id -ErrorAction SilentlyContinue){try{Stop-Process -Id $id -ErrorAction SilentlyContinue}catch{}}}; @{roots=$pids} | ConvertTo-Json -Compress`;return !!psJson(script,12000)}
function launchNormalEdge(){if(process.platform!=='win32')return false;try{const p=spawn(edgeExe(),['--restore-last-session'],{detached:true,stdio:'ignore',windowsHide:false});p.unref();return true}catch{return false}}
export async function diagnoseSameEdge(){const active=readActivePort();const fixed=await httpJson(Number(settings.browserBridge?.remoteDebugPort||9222));const roots=personalEdges();const stale=roots.some(x=>/--remote-debugging-port(?:=|\s)9222/i.test(x.commandLine))&&!fixed.ok&&!active;return {at:nowIso(),activePort:active?.port||null,fixedPortOk:!!fixed.ok,roots,staleDebugFlags:stale,legacySources:legacySources(),remoteDebugReady:!!active||!!fixed.ok}}
export async function repairSameEdgeConnection({force=false,onEvent=()=>{}}={}){
 const before=await diagnoseSameEdge();if(before.remoteDebugReady)return {ok:true,repaired:false,before,after:before,reason:'ALREADY_READY'};
 const state=readRepair(),bk=bootKey();if(state.bootKey!==bk){state.bootKey=bk;state.restarts=0}
 const max=Math.max(1,Number(settings.browserBridge?.controlledRestartMaxPerBoot||1));
 if(!force&&state.restarts>=max)return {ok:false,repaired:false,before,reason:'CONTROLLED_RESTART_LIMIT_REACHED'};
 if(!settings.browserBridge?.controlledRestartAllowed)return {ok:false,repaired:false,before,reason:'CONTROLLED_RESTART_DISABLED'};
 if(!before.staleDebugFlags&&!force)return {ok:false,repaired:false,before,reason:'NO_STALE_DEBUG_FLAGS_DETECTED'};
 onEvent('EDGE_REPAIR_BACKUP','Respaldando sesión Edge antes del reinicio controlado');const backup=settings.browserBridge?.sessionBackupBeforeRestart?backupSessions():null;
 const legacy=before.legacySources||[];const neutralized=neutralizeLegacy(legacy);onEvent('EDGE_REPAIR_LEGACY','Neutralizados launchers legacy de Edge: '+neutralized.filter(x=>x.disabled).length);
 onEvent('EDGE_REPAIR_RESTART','Cerrando SOLO Edge personal una vez; Core/browser aislado no se toca');gracefulClosePersonalEdge();await sleep(1800);const launched=launchNormalEdge();state.restarts++;state.lastAt=nowIso();state.backup=backup;writeRepair(state);await sleep(9000);
 let after=await diagnoseSameEdge();for(let i=0;i<8&&!after.remoteDebugReady;i++){await sleep(1500);after=await diagnoseSameEdge()}
 const result={ok:after.remoteDebugReady,repaired:true,before,after,backup,neutralized,launched,reason:after.remoteDebugReady?'REMOTE_DEBUG_READY_AFTER_CONTROLLED_RESTART':'EDGE_RESTARTED_BUT_REMOTE_DEBUG_NOT_READY'};try{fs.writeFileSync(evidenceFile(),JSON.stringify(result,null,2),'utf8')}catch{};return result
}
